services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3232:3232"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3232
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3232" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - modelos-publicidad

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Montamos la configuración personalizada
      - /etc/ssl/certs/modelmatch/modelmatch_net_2025.fullchain.crt:/etc/ssl/certs/modelmatch/modelmatch_net_2025.fullchain.crt
      - /etc/ssl/private/model/modelmatch_2025.key:/etc/ssl/private/model/modelmatch_2025.key
    ports:
      - "80:80" # Para HTTP
      - "443:443" # Para HTTPS (debes agregar esta línea)
    depends_on:
      - web
    networks:
      - modelos-publicidad

networks:
  modelos-publicidad:
    external: true
